### ISSUE TITLE
`decimal`-parameter for reading CSV-files?

### ISSUE THREAD

**Issue by roland-KA** [TidierOrg/TidierFiles.jl#11]
Is there a `decimal`-parameter (as in CSV.jl) to specify if the fractional part of decimal numbers is separated by '.' (like 3.14) or by ',' (like 3,14) when reading CSV files?

**Comment by drizk1** [comment]
I will check but I'm not sure presently. Do you have a dataset you need to read w that format?

**Comment by roland-KA** [comment]
In Germany (and in many other European countries) the comma-separated format is standard. So it's an every-day use-case.

**Comment by drizk1** [comment]
Ok. If you have an easily accessible small dataset, please pass it along so I can begin testing with it as I figure out what csv.jl offers and how to make tidierfiles support it

**Comment by roland-KA** [comment]
[CommaExample.csv](https://github.com/user-attachments/files/16112819/CommaExample.csv)

This is an example with three columns A, B and C, where B and C are floating-point numbers using a comma-separator. The column-separator in these files is a semicolon (so that there isn't a confusion with the comma-separator within the floating-point numbers).

**Comment by drizk1** [comment]
ok, so [there is an argument in csv.jl](https://csv.juliadata.org/stable/reading.html#decimal:~:text=DateFormat-,decimal,-An%20ASCII%20Char) to choose what the decimal is. 

`read_csv`, `read_delim` and `read_tsv` do not yet support that additional argument, but I'll get that sorted out and added soon for all three

**Comment by drizk1** [comment]
with v.1.2 which i should be on the registry in 20 mins or so 
there are two ways to do it
- `read_csv2` defaults to `delim = ';'` and `decimal = ','`
-  for more control you can use `read_delim` as well
```
julia> read_csv2("path/to/CommaExample.csv")
10×3 DataFrame
 Row │ A        B        C       
     │ String1  Float64  Float64 
─────┼───────────────────────────
   1 │ j           90.0     89.0
   2 │ t           52.0      7.0
   3 │ z           47.0     85.0
   4 │ r           72.0     67.0
   5 │ j           50.0     85.0
   6 │ x            5.0     29.0
   7 │ a           84.0      7.0
   8 │ t           38.0     28.0
   9 │ w           96.0     42.0
  10 │ a           12.0     62.0

julia> read_delim("path/to/CommaExample.csv", decimal = ',', delim = ';')
10×3 DataFrame
 Row │ A        B        C       
     │ String1  Float64  Float64 
─────┼───────────────────────────
   1 │ j           90.0     89.0
   2 │ t           52.0      7.0
   3 │ z           47.0     85.0
   4 │ r           72.0     67.0
   5 │ j           50.0     85.0
   6 │ x            5.0     29.0
   7 │ a           84.0      7.0
   8 │ t           38.0     28.0
   9 │ w           96.0     42.0
  10 │ a           12.0     62.0

```

**Comment by roland-KA** [comment]
Wow, that went fast! Thank you very much 😊👍
