### ISSUE TITLE
add `import` `export` like rio

### ISSUE THREAD

**Issue by drizk1** [TidierOrg/TidierFiles.jl#15]
add import and export that detect extension and dispatch the correct function but it may need a different name because of base import. it seems it wont allow it, but working version exists. 

perhaps `import_tf`, `import_data`, `pan_import`, `load`? but im open to anything

**Comment by kdpsingh** [comment]
Love this idea. I would suggest `read_file()` and `write_file()`. I realize that's different than `rio` but keeps the naming consistent.

**Comment by drizk1** [comment]
Love the name. The that's what we'll do
