### ISSUE TITLE
Function to list all files in a directory

### ISSUE THREAD

**Issue by vituri** [TidierOrg/TidierFiles.jl#18]
Not really an issue!

I often find myself redefining something like this:

```
function list_files(path="", pattern="")
    files =
        @chain begin
            map(walkdir(path)) do (root, dirs, files)
                joinpath.(root, files)
            end
            reduce(vcat, _)
            filter(x -> occursin(pattern, x), _)
        end

    files
end;
```

inspired by the list.files from base R. Many times I just want to list all the files in folders and subfolders, which optionally satisfy some string pattern. Is TidierFiles the place to define and export it? What do you think?

**Comment by drizk1** [comment]
I think this is pretty neat and definitely see the utility 

Just out of curiosity, it possible to write the function with the using `@chain` to avoid adding a new dependency ?

**Comment by drizk1** [comment]
here is a `@chain` free version, @vituri . off some prelim testing it seems to yield the same results.

```
function list_files(path = "", pattern = "")
    files = map(walkdir(path)) do (root, dirs, files)
        joinpath.(root, files)
    end
    files = reduce(vcat, files)
    files = filter(x -> occursin(pattern, x), files)
    return files
end
```
i think this definitely fits in to tidierfiles. Would u like to throw in a PR for it? I can if not

**Comment by vituri** [comment]
Thanks, @drizk1 ! The function looks fine. I think you can do the PR, because you probably know the best place to put this function.

After the merge, I will download the github version of the package and never again will need to redefine this thing!! A dream coming true!

**Comment by drizk1** [comment]
alright go head and give the new branch a shot. 

if it works as u need it to, ill go ahead and merge and release

```
using Pkg; Pkg.add(url = "https://github.com/TidierOrg/TidierFiles.jl", rev = "add-list_files")
```

**Comment by vituri** [comment]
![image](https://github.com/user-attachments/assets/7a031882-2d3f-49fc-9c10-dd829bffb8a9)

Looks good! Thanks, @drizk1 !
