### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by pdimens** [TidierOrg/TidierFiles.jl#2]
New package, new symbology-- congrats on the new addition! If you give me until the end of the week, I can draft an icon for this, unless someone else is already working on it.

**Comment by drizk1** [comment]
Wow you're fast! It's all you. Can't wait to see what you drum up. Thank you!

**Comment by pdimens** [comment]
First idea, sorta like a hand of playing cards 
![image](https://github.com/TidierOrg/TidierFiles.jl/assets/19176506/49fd093d-0f78-41c1-aebe-c54445020cd5)

**Comment by pdimens** [comment]
Or no specific file format names
![image](https://github.com/TidierOrg/TidierFiles.jl/assets/19176506/3ba198a9-b2a6-48ea-b73b-3029249f3052)

**Comment by drizk1** [comment]
i love the colors and idea on these. Would it be possible to change the XLSX to a tsv (just to keep things symmetrical at 3 characters across the cards) and mb add the glasses too? not sure if adding the glasses would make it too busy but curious to see

**Comment by pdimens** [comment]
![image](https://github.com/TidierOrg/TidierFiles.jl/assets/19176506/5a41ff74-2656-46b8-8ea6-d785c8cad71a)

**Comment by drizk1** [comment]
This looks great ! Wow. Going to loop in @kdpsingh to see if he has any other thoughts, but otherwise I think it's repo ready. 

Side note: ok the horizon there's going be another package for databases, and we'd love for you to do that icon as well if you have the bandwidth

**Comment by kdpsingh** [comment]
I LOVE the logo! @pdimens strikes again!

**Comment by pdimens** [comment]
@drizk1 just ping me in an issue on the database repo to make me aware of it :)
