### ISSUE TITLE
col_types missing from read_csv() but present in docs

### ISSUE THREAD

**Issue by KadeG** [TidierOrg/TidierFiles.jl#21]
col_types appears to be missing from read_csv() but present in the docs: https://tidierorg.github.io/TidierFiles.jl/latest/reference/#TidierFiles.read_csv-Tuple{Any}

Tangential: it would be awesome if we can pass through some of the other options present in CSV.read like normalizenames, etc.

**Comment by drizk1** [comment]
Hmm idk what happened there but we can def add support for both. 

Just wondering when using r, what for your ideal `col_types` use look like? It's not one I frequently have used

**Comment by KadeG** [comment]
I've actually never used Tidier in R, only Tidier.jl because it's awesome. But I frequently use `col_types` when dealing with data with leading zeros: it gets interpreted as `Int` which strips the leading zeros so you can't fix it after reading it in. Should be able to pass to `CSV.File`: https://csv.juliadata.org/stable/examples.html#types_example

Would it be easier to have a helper function to interpret passing through the various extra arguments `CSV.File` can take?

**Comment by drizk1** [comment]
Oh wow, I love that. 

So basically, if I'm understanding correctly, there are times when you need to specify the column type you are reading for a select couple columns? 

It might be easier to have a helper function.  

I'm open to any approach really. 

If you have a plan in mind, feel free to give it a spin, if not i can piece something together

**Comment by drizk1** [comment]
Alright, with v.1.6 all the features you requested should be available. 

I'm going to close this issue for now but plz reopen / open a new issue if there's anything not working / something else you need.
