### ISSUE TITLE
Add support for parquet and arrow

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/TidierFiles.jl#6]

**Comment by kdpsingh** [comment]
The main use case for working with arrow is to be able to work on Arrow frames that have been instantiated into shared memory. So I eventually need to add Arrow support to TidierData for working with arrow in a way that does not produce a copy of the entire data frame.

For now, the idea would be that we will instantiate both types of files as a data frame in memory.

**Comment by drizk1** [comment]
Sounds good. Reading them as dfs will be pretty straightforward. 

I'm curious to see what making tidierdata work directly with arrow tables will look like
